name: valorantmaster
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  page_transition: ^2.1.0
  shared_preferences: ^2.0.6
  google_fonts: ^2.2.0

  # フォントライブラリ
  google_fonts: ^2.3.1
  fonts:
  - family: NotoSerifJP
    fonts:
      - asset: fonts/NotoSerifJP-Black.otf
        weight: 900
      - asset: fonts/NotoSerifJP-Bold.otf
        weight: 700
      - asset: fonts/NotoSerifJP-ExtraBold.otf
        weight: 800
      - asset: fonts/NotoSerifJP-Light.otf
        weight: 300
      - asset: fonts/NotoSerifJP-Medium.otf
        weight: 500
      - asset: fonts/NotoSerifJP-Regular.otf
        weight: 400
      - asset: fonts/NotoSerifJP-SemiBold.otf
        weight: 600
      - asset: fonts/NotoSerifJP-Thin.otf
        weight: 100

flutter:
  uses-material-design: true
  assets:
    - images/
